const GITHUB_API = "https://api.github.com";

export interface GithubFile {
  path: string;
  content: string;
}

async function githubFetch<T = unknown>(
  path: string,
  options: { method?: string; body?: unknown } = {}
): Promise<T> {
  const token = process.env.GITHUB_PAT;
  if (!token) throw new Error("GITHUB_PAT not configured");

  const res = await fetch(`${GITHUB_API}${path}`, {
    method: options.method ?? "GET",
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
    },
    body: options.body ? JSON.stringify(options.body) : undefined,
  });

  if (!res.ok) {
    const err = await res.text().catch(() => "Unknown error");
    throw new Error(`GitHub API ${res.status} on ${path}: ${err}`);
  }

  return res.json() as Promise<T>;
}

export async function getGithubLogin(): Promise<string> {
  const user = await githubFetch<{ login: string }>("/user");
  return user.login;
}

export async function createClientRepo(
  slug: string,
  description: string,
  files: GithubFile[]
): Promise<{ repoUrl: string; cloneUrl: string; repoName: string }> {
  const login = await getGithubLogin();
  const repoName = `client-${slug}`;

  // 1. Create empty private repo
  const repo = await githubFetch<{ html_url: string; clone_url: string }>(
    "/user/repos",
    {
      method: "POST",
      body: {
        name: repoName,
        description,
        private: true,
        auto_init: false,
        has_issues: false,
        has_wiki: false,
        has_projects: false,
      },
    }
  );

  // 2. Create blobs in batches of 5 to avoid rate limiting
  const blobShas: { path: string; sha: string }[] = [];
  for (let i = 0; i < files.length; i += 5) {
    const batch = files.slice(i, i + 5);
    const results = await Promise.all(
      batch.map(async (file) => {
        const blob = await githubFetch<{ sha: string }>(
          `/repos/${login}/${repoName}/git/blobs`,
          {
            method: "POST",
            body: {
              content: Buffer.from(file.content, "utf-8").toString("base64"),
              encoding: "base64",
            },
          }
        );
        return { path: file.path, sha: blob.sha };
      })
    );
    blobShas.push(...results);
  }

  // 3. Create tree from all blobs
  const tree = await githubFetch<{ sha: string }>(
    `/repos/${login}/${repoName}/git/trees`,
    {
      method: "POST",
      body: {
        tree: blobShas.map(({ path, sha }) => ({
          path,
          mode: "100644",
          type: "blob",
          sha,
        })),
      },
    }
  );

  // 4. Create orphan commit (no parents — this is the initial commit)
  const commit = await githubFetch<{ sha: string }>(
    `/repos/${login}/${repoName}/git/commits`,
    {
      method: "POST",
      body: {
        message: `Initial blueprint scaffold — ${slug}\n\nGenerated by Marchio Blueprint System`,
        tree: tree.sha,
        parents: [],
      },
    }
  );

  // 5. Create main branch pointing at the new commit
  await githubFetch(`/repos/${login}/${repoName}/git/refs`, {
    method: "POST",
    body: {
      ref: "refs/heads/main",
      sha: commit.sha,
    },
  });

  return {
    repoUrl: repo.html_url,
    cloneUrl: repo.clone_url,
    repoName,
  };
}
